#!/bin/bash
#
# vim-anywhere - use Vim whenever, wherever
# Author: Chris Knadler
# Homepage: https://www.github.com/cknadler/vim-anywhere
#
# Open a temporary file with Vim. Once Vim is closed, copy the contents of that
# file to the system clipboard.

###
# defs
###

err() { echo -e "$@" 1>&2; }

require_file_exists() {
  if [ ! -e $1 ]; then
    err "$1 does not exist. ${@:2}"
    exit 1
  fi
}


###
# run
###

AW_PATH=$HOME/.vim-anywhere
TMPFILE_DIR=/tmp/vim-anywhere
TMPFILE=$TMPFILE_DIR/doc-$(date +"%y%m%d%H%M%S")
VIM_OPTS=--no-fork

mkdir -p $TMPFILE_DIR
# touch $TMPFILE
# xdotool key "ctrl+a"
# xdotool key "ctrl+c"
xclip -o > $TMPFILE

chmod o-r $TMPFILE # Make file only readable by you
nvim-gtk $VIM_OPTS $TMPFILE
cat $TMPFILE | xclip -selection clipboard
# xdotool key "ctrl+v"

